"""This file contains all the constants to be used in the project."""
TITLE = "Title"
LINKS = "Link"
DATE = "Date"
DRIVER_PATH = "C:/Users/Mehul/Desktop/edgedriver_win64/edgedriver_win64"
HTML_LIB = "html5lib"
NURL = "https://www.naukri.com/web-scraping-jobs-in-delhi-ncr-"
URL = "https://www.bea.gov"
ALL_LINKS = "more-link form-group"
HREF = "href"
DIV_TAG = "div"
ANCHOR_TAG = "a"
VIEW_CONTENT = "view-content"
CSV_FILE_NAME = "Blogs.csv"
WRITE = "w"
PATH = "dummy-data-product\src\dependencies\scraping"